---
- hosts: localhost
  become: true
  vars:
    packages:
      - cifs-utils
      - exfatprogs
      - eza
      - figlet
      - firefox
      - fonts-font-awesome
      - fzf
      - git
      - gnome-screenshot
      - gnome-tweaks
      - htop
      - jq
      - nvidia-driver-580-open
      - neofetch
      - neovim
      - openssh-server
      - pass
      - pwgen
      - speedtest-cli
      - timeshift
      - vlc
      - xclip
      - xdg-user-dirs
      - zsh

  tasks:
    - name: Install apt packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
