---
- name: Add launcher
  become: true
  hosts: localhost
  tasks:
    - name: Add repository universe
      shell: |
        add-apt-repository universe -y
        add-apt-repository ppa:agornostal/ulauncher -y

- name: AWS CLI
  hosts: localhost
  tasks:
    - name: Download awscli
      get_url:
        dest: /tmp/awscliv2.zip
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        mode: 0644
        force: false

    - name: Create temp folder
      file:
        path: /tmp/awscliv2
        state: directory
        mode: 0755

    - name: Extract awscli
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/awscliv2
        remote_src: yes
        creates: /tmp/awscliv2/aws/install

    - name: Run bundled installer
      become: true
      command: /tmp/awscliv2/aws/install -i /usr/local/aws-cli -b /usr/local/bin
      args:
        creates: /usr/local/bin/aws

- name: .NET Runtime
  hosts: localhost
  tasks:
    - name: Download .NET runtime
      get_url:
        force: true
        mode: 0755
        dest: "{{ ansible_facts['env']['HOME'] }}/Downloads/dotnet-install.sh"
        url: https://dot.net/v1/dotnet-install.sh
      become: false

    - name: Install .NET runtime
      become: true
      ansible.builtin.command:
        argv:
          - bash
          - "{{ ansible_facts['env']['HOME'] }}/Downloads/dotnet-install.sh"
          - --install-dir
          - /usr/share/dotnet
          - --version
          - 8.0.415
      environment:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

- name: Golang
  hosts: localhost
  tasks:
    - name: Download golang
      get_url:
        force: false
        mode: 0755
        dest: /tmp/go1.25.3.linux-amd64.tar.gz
        url: https://go.dev/dl/go1.25.3.linux-amd64.tar.gz
      become: false

    - name: Install golang
      become: true
      shell: |
        rm -rf /usr/local/go
        tar -C /usr/local -xzf /tmp/go1.25.3.linux-amd64.tar.gz
      args:
        creates: /usr/local/go/bin/go
        executable: /bin/bash

    - name: Add terraform repository
      become: true
      copy:
        dest: /etc/apt/sources.list.d/hashicorp.list
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com noble main
        mode: 0644

    - name: Download Hashicorp's GPG key
      become: true
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

    - name: Verify Hashicorp's GPG fingerprint
      shell: |
        gpg --no-default-keyring \
          --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
          --fingerprint
      register: gpg_details
      changed_when: false

- name: Install ollama
  hosts: localhost
  tasks:
    - name: Download install script
      get_url:
        url: https://ollama.com/install.sh
        dest: /tmp/ollama-install.sh
        mode: 0755

    - name: Run install script
      become: true
      command: /tmp/ollama-install.sh
      args:
        creates: /usr/local/bin/ollama