- hosts: localhost
  gather_facts: true

  vars:
    home_dir: "{{ lookup('env','HOME') }}"
    p10k_dir: "{{ home_dir }}/powerlevel10k"
    zsh_autosuggestions_path: "{{ home_dir }}/.zsh/zsh-autosuggestions"
    zshrc_path: "{{ home_dir }}/.zshrc"
  tasks:
    - name: Ensure zsh is installed
      become: true
      apt:
        name: zsh
        state: present
        update_cache: yes

    - name: Ensure .zsh directory exists
      file:
        path: "{{ home_dir }}/.zsh"
        state: directory
        mode: "0755"

    - name: Clone Powerlevel10k repo
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ p10k_dir }}"
        depth: 1
        update: yes

    - name: Clone zsh-autosuggestions repo
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "{{ zsh_autosuggestions_path }}"
        depth: 1
        update: yes

    - name: Configure .zshrc block
      blockinfile:
        path: "{{ zshrc_path }}"
        marker: "# {mark} ANSIBLE_MANAGED_P10K"
        create: yes
        insertafter: EOF
        block: |
          if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
            source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
          fi

          [[ -f "{{ p10k_dir }}/powerlevel10k.zsh-theme" ]] && source "{{ p10k_dir }}/powerlevel10k.zsh-theme"
          [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
          [[ -f ~/.zsh_aliases ]] && source ~/.zsh_aliases
          [[ -f ~/.zsh_exports ]] && source ~/.zsh_exports
          [[ -f "{{ zsh_autosuggestions_path }}/zsh-autosuggestions.zsh" ]] && source "{{ zsh_autosuggestions_path }}/zsh-autosuggestions.zsh"

          HISTFILE=~/.zsh_history
          HISTSIZE=10000
          SAVEHIST=10000
          setopt appendhistory

    - name: Change default shell to zsh
      become: true
      user:
        name: "{{ ansible_facts.user_id }}"
        shell: /usr/bin/zsh

    # -----------------------------
    # ZSH ALIASES / EXPORTS
    # -----------------------------

    - name: Write .zsh_aliases
      copy:
        dest: "{{ home_dir }}/.zsh_aliases"
        mode: "0644"
        content: |
          alias ls='eza -a --icons=always'
          alias la='eza -lia --icons=always'
          alias ll='eza -l --icons=always'
          alias lt='eza --tree --level=1 --icons=always'
          alias cl='clear'
          alias home='cd ~/'
          alias py='python3'
          alias rs='exec $SHELL -l'

    - name: Write .zsh_exports
      copy:
        dest: "{{ home_dir }}/.zsh_exports"
        mode: "0644"
        content: |
          export DOCKER_HOST=unix:///run/user/1000/docker.sock
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          export PATH=$PATH:/usr/local/go/bin
          export GOPATH=~/go
          export PATH="$PATH:$(go env GOPATH)/bin"
          export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"
          export PYTHONPATH="$PWD/lib:$PYTHONPATH"
          export PATH="$PATH:$HOME/.local/bin"
